name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25518
          chmod 600 ~/.ssh/id_ed25518

      - name: Add server to known_hosts
        run: |
           ssh-keyscan -p 10022 62.183.54.203 >> ~/.ssh/known_hosts
      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25518 root_server@62.183.54.203 -p 10022 'cd /home/root_server/forum/forum && git pull origin main'

